// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_y4XSu_PuV6NkG8Jsio6P27M7T_zhgSg',
    appId: '1:37389460630:web:4dbf4d073c00c2d1f84eb7',
    messagingSenderId: '37389460630',
    projectId: 'chatapp-c20f2',
    authDomain: 'chatapp-c20f2.firebaseapp.com',
    storageBucket: 'chatapp-c20f2.appspot.com',
    measurementId: 'G-J0RBH5DP0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX0HpPFw02EttoACJn52jowZBVZvLwGw0',
    appId: '1:37389460630:android:18bb276010dc07baf84eb7',
    messagingSenderId: '37389460630',
    projectId: 'chatapp-c20f2',
    storageBucket: 'chatapp-c20f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxt0gRu546L8uPwl3zw7yeLPuSukngVxk',
    appId: '1:37389460630:ios:bf7aab7a258f3c45f84eb7',
    messagingSenderId: '37389460630',
    projectId: 'chatapp-c20f2',
    storageBucket: 'chatapp-c20f2.appspot.com',
    iosClientId: '37389460630-gmkisgc7ngb4jv092o1596pln5ja4pl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxt0gRu546L8uPwl3zw7yeLPuSukngVxk',
    appId: '1:37389460630:ios:bf7aab7a258f3c45f84eb7',
    messagingSenderId: '37389460630',
    projectId: 'chatapp-c20f2',
    storageBucket: 'chatapp-c20f2.appspot.com',
    iosClientId: '37389460630-gmkisgc7ngb4jv092o1596pln5ja4pl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
